nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
ichat:
    build: ./
    hostname: ichat
    restart: always
    volumes:
        - /usr/src/app/public/files
    links:
        - "dbhost"
    ports:
      - "3000:3000"
    environment:
        - VIRTUAL_HOST=ichat.yongbuzhixi.com
        - RDB_HOST=dbhost
        - RDB_PORT=28015
        - RDB_DB=ichat
#################
dbhost:
    image: rethinkdb:latest
    hostname: dbhost
    restart: always
    volumes_from:
        - storage-db
    ports:
        - "80"
    command: ["rethinkdb", "--bind", "all", "--http-port", "80"] ##--no-http-admin 
    environment:
        - VIRTUAL_HOST=rethinkdb.yongbuzhixi.com
#################
storage-db: #debian:jessie
    image: debian:jessie
    volumes:
        - /data
